---
title: "Intro to RMarkdown"
author: Kale
output: html_document
---
```{r setup}
knitr::opts_chunk$set(echo = FALSE)
library(dplyr)
library(lubridate)
library(ggplot2)
library(tidyr)
```


##Purpose 
Demonstrate how to use RMarkdown using gapminder data. We will make a few plots, show some code, and play around with formatting in RMarkdown.
```{r biketown, include=FALSE}
biketownjul18 <- read.csv("data/2018_07.csv", stringsAsFactors = F) 
str(biketownjul18)

avg_dis_by_sub <- biketownjul18 %>%
  group_by(PaymentPlan) %>%
  summarise(mean_dm = mean(Distance_Miles))

avg_dis_fig <- avg_dis_by_sub %>%
  ggplot(aes(x = PaymentPlan, y = mean_dm, fill=PaymentPlan)) + # need ot use + in gg
  geom_bar(stat = "identity") #to show value, therwise will get count of
avg_dis_fig
```

```{r avg_dis_fig, echo=FALSE}
avg_dis_fig
```
```{r avg_dis_table}
knitr::kable(avg_dis_by_sub, options = list(
  pagelength = 15), caption = 'Table 1: Table of Values')
```
## Including Plots

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
